server:
  port: 8080

spring:
  application:
    name: gateway-service

  cloud:
    gateway:
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
      routes:
        - id: login-service
          uri: http://localhost:8081
          predicates:
            - Path=/login/**
          filters:
            - StripPrefix=1
            - AddRequestHeader=X-GATEWAY-AUTH, secret-123

        - id: ticket-service
          uri: http://localhost:8082
          predicates:
            - Path=/tickets/**
          filters:
            - StripPrefix=1

        - id: scraping-service
          uri: http://localhost:8000
          predicates:
            - Path=/scrape/**
          filters:
            - StripPrefix=1
            - AddRequestHeader=X-GATEWAY-AUTH, secret-123

      globalcors:
        corsConfigurations:
          '[/**]': # apply to every path
            allowedOrigins:
              - http://localhost:5173
            allowedOriginPatterns:
              - "http://localhost:*"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
            allowedHeaders:
              - Authorization
              - Content-Type
            allowCredentials: true
            maxAge: 3600

springdoc:
  swagger-ui:
    urls:
      - name: Login Service
        url: /login/v3/api-docs
  api-docs:
    group-configs:
      - group: login-service
        paths-to-match: /login/api/auth/**, /login/health=

jwt:
  secret: y5L@9N9a&fH^Gv7mWz@qPxJ!sV*D3#cB$uMn7Rz%LgXeK4AvTqZ0^WhbUo2KmNtp
  algorithm: HS512
  whitelist:
    - /login/api/auth/login
    - /login/api/auth/register
    - /login/swagger-ui/**
    - /login/v3/api-docs/**
    - /swagger-ui/**
    - /v3/api-docs/**
    - /api/health
